---
title: "ChessScriptAnalysis"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
```


```{r}
chess_games = read.csv('../Data/chess_games.csv')
head(chess_games)
```

Get one 
```{r}
script1 = chess_games$moves[3]
```

```{r}
script1_split = strsplit(script1,"[[:space:]]")[[1]]
script1_split

script1_white_moves = script1_split[c(TRUE, FALSE)]
script1_black_moves = script1_split[c(FALSE, TRUE)]
```

Find which piece a certain piece took and aggregate for a game
Bxf8 means that a bishop took a piece on f8

```{r}
test_move = "Bxf8"
take = "x"

grepl(take, test_move, fixed=TRUE)
strsplit(test_move, "[x]")[[1]][2]

test_move2 = "Rf8"
strsplit(test_move2, "[x]")[[1]]

grepl('f8', test_move, fixed = TRUE)
strsplit(test_move2, "f8")[[1]][1]

str_detect("b", "[[:lower:]]")

str_replace(test_move, 'x', '')
```


```{r}
script1
```

helper function to translate string piece name to current value
```{r}
name2value_func = function(piece_scriptname) {
  piece_value = 0
  
  if(piece_scriptname == "" || str_detect(piece_scriptname, "[[:lower:]]")) {
    piece_value = 1
  } else if (piece_scriptname == "N" || piece_scriptname == "B") {
    piece_value = 3
  } else if (piece_scriptname == "R") {
    piece_value = 5
  } else if (piece_scriptname == "Q") {
    piece_value = 9
  }
  
  return(piece_value)
}

name2value_func("")

scriptname2fullname_func = function(piece_scriptname) {
  if(piece_scriptname == "" || str_detect(piece_scriptname, "[[:lower:]]")) {
    fullname = "Pawn"
  } else if (piece_scriptname == "N") {
    fullname = "Knight"
  } else if (piece_scriptname == "B") {
    fullname = "Bishop"
  } else if (piece_scriptname == "R") {
    fullname = "Rook"
  } else if (piece_scriptname == "Q") {
    fullname = "Queen"
  }
  
  return(fullname)
}

scriptname2fullname_func("")
```

To-do
1. ADD CHECKS
```{r}
take = "x"
game_takes = as.data.frame(matrix(nrow = 6, ncol = 3))
game_takes[is.na(game_takes)] = 0
rownames(game_takes) = c('Pawn', 'Knight', 'Bishop', 'Rook', 'Queen', 'King')
colnames(game_takes) = c('num_moves', 'num_pieces_taken', 'value_pieces_taken')
game_takes$list_pieces_taken = ""

for (i in c(1:length(script1_white_moves))) {
  white_move = script1_white_moves[i]
  #Step 1: Find the moves where a piece was taken (all the moves that have an x in the term)
  if(grepl(take, white_move, fixed=TRUE)) {
    #Step 2: Extract the move number of the take move and the piece that took \
    #Example: axb5 leads to the piece_capturer = a & board_loc = b5
    move_num <<- i
    piece_capturer <<- strsplit(white_move, "[x]")[[1]][1]
    board_loc <<- strsplit(white_move, "[x]")[[1]][2]
    #Step 3: Identify which piece it took, if piece_taken is blank, its a pawn
    for (j in c(move_num-1:1)) {
      black_move <- script1_black_moves[j]
      if (grepl(board_loc, black_move, fixed = TRUE)) {
        print(black_move)
        piece_taken = strsplit(black_move, board_loc)[[1]][1]
        #take out excess x (which indicated a previous take)
        piece_taken <<- str_replace(piece_taken, 'x', '')
        break
      }
      ##Edge case: piece that was taken has not moved yet
    }
  }
  #step 4: Add values to dataframe
  if(i == move_num) {
    piece_capturer_name = scriptname2fullname_func(piece_capturer)
    piece_taken_name = scriptname2fullname_func(piece_taken)
    piece_taken_value = name2value_func(piece_taken)
    
    game_takes[piece_capturer_name, 'num_pieces_taken'] = 
      game_takes[piece_capturer_name, 'num_pieces_taken'] + 1
    
    game_takes[piece_capturer_name, 'value_pieces_taken'] = 
      game_takes[piece_capturer_name, 'value_pieces_taken'] + piece_taken_value
    
    string = game_takes[piece_capturer_name, 'list_pieces_taken']
    new_string = paste(string, piece_taken_name)
    game_takes[piece_capturer_name, 'list_pieces_taken'] = new_string
    
  }
}

game_takes
```

