---
title: "ChessScriptAnalysisExample"
output:
  pdf_document: default
---

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
```


```{r}
chess_games = read.csv('../Data/chess_games.csv')
head(chess_games)
```

Get one 
```{r}
script1 = chess_games$moves[3]
```

```{r}
script1_split = strsplit(script1,"[[:space:]]")[[1]]
script1_split

script1_white_moves = script1_split[c(TRUE, FALSE)]
script1_black_moves = script1_split[c(FALSE, TRUE)]
```

Functions needed for such, test code examples
```{r}
test_move = "Bxf8"
take = "x"

grepl(take, test_move, fixed=TRUE)
strsplit(test_move, "[x]")[[1]][2]

test_move2 = "Rf8"
strsplit(test_move2, "[x]")[[1]]

grepl('f8', test_move, fixed = TRUE)
strsplit(test_move2, "f8")[[1]][1]

str_detect("b", "[[:lower:]]")

str_replace(test_move, 'x', '')
```

Full moves for reference
```{r}
script1
script1_white_moves
script1_black_moves
```

helper function to translate string piece name to current value
```{r}
name2value_func = function(piece_scriptname) {
  piece_value = 0
  
  if(piece_scriptname == "" || str_detect(piece_scriptname, "[[:lower:]]")) {
    piece_value = 1
  } else if (piece_scriptname == "N" || piece_scriptname == "B") {
    piece_value = 3
  } else if (piece_scriptname == "R") {
    piece_value = 5
  } else if (piece_scriptname == "Q") {
    piece_value = 9
  }
  
  return(piece_value)
}

name2value_func("a")
name2value_func("B")
name2value_func("Q")
name2value_func("")
```

helper function to translate string piece name to full name (to add to nicer dataframe)
```{r}
scriptname2fullname_func = function(piece_scriptname) {
  if(piece_scriptname == "" || str_detect(piece_scriptname, "[[:lower:]]")) {
    fullname = "Pawn"
  } else if (piece_scriptname == "N") {
    fullname = "Knight"
  } else if (piece_scriptname == "B") {
    fullname = "Bishop"
  } else if (piece_scriptname == "R") {
    fullname = "Rook"
  } else if (piece_scriptname == "Q") {
    fullname = "Queen"
  } else if (piece_scriptname == "K") {
    fullname = "King"
  }
  
  return(fullname)
}

scriptname2fullname_func("a")
scriptname2fullname_func("B")
scriptname2fullname_func("Q")
scriptname2fullname_func("")
```

Helper function to tell us where piece start (use for script analysis)
```{r}
original_piece_locations = function(piece_color, piece_loc) {
  piece = "None"
  if(piece_color == 'white') {
    if (piece_loc %in% c('a2', 'b2', 'c2', 'd2', 'e2', 'f2', 'g2', 'h2')) {
      piece = ""
    } else if (piece_loc %in% c('a1', 'h1')) {
      piece = "R"
    } else if (piece_loc %in% c('b1', 'g1')) {
      piece = "N"
    } else if (piece_loc %in% c('c1', 'f1')) {
      piece = "B"
    } else if (piece_loc == 'd1') {
      piece = "Q"
    } else if (piece_loc == 'e1') {
      piece = "K"
    }}
  else {
    if (piece_loc %in% c('a7', 'b7', 'c7', 'd7', 'e7', 'f7', 'g7', 'h7')) {
      piece = ""
    } else if (piece_loc %in% c('a8', 'h8')) {
      piece = "R"
    } else if (piece_loc %in% c('b8', 'g8')) {
      piece = "N"
    } else if (piece_loc %in% c('c8', 'f8')) {
      piece = "B"
    } else if (piece_loc == 'd8') {
      piece = "Q"
    } else if (piece_loc == 'e8') {
      piece = "K"
    }}
  
  return(piece)
}   


original_piece_locations("white", "e2")
original_piece_locations("white", "f1")
original_piece_locations("black", "g7")
original_piece_locations("black", "a4")
```


```{r}
#initialize dataframe of takes 
game_takes = as.data.frame(matrix(nrow = 6, ncol = 4))
game_takes[is.na(game_takes)] = 0
rownames(game_takes) = c('Pawn', 'Knight', 'Bishop', 'Rook', 'Queen', 'King')
colnames(game_takes) = c('num_moves', 'num_checks', 'num_pieces_taken', 'value_pieces_taken')
game_takes$list_pieces_taken = ""


#Fill in column for number of moves

for (i in c(1:length(script1_white_moves))) {
  move = script1_white_moves[i]
  first_char = substr(move, 1, 1)
  piece = scriptname2fullname_func(first_char)
  
  
  game_takes[piece, 'num_moves'] = 
    game_takes[piece, 'num_moves'] + 1
  }

#Fill in column for number of checks

for (i in c(1:length(script1_white_moves))) {
  move = script1_white_moves[i]
  
  if((grepl("+", move, fixed = TRUE)) | (grepl("#", move, fixed = TRUE))) {
    first_char = substr(move, 1, 1)
    piece = scriptname2fullname_func(first_char)
    
    
    game_takes[piece, 'num_checks'] = 
      game_takes[piece, 'num_checks'] + 1
  }
}

#Fill in columns num_pieces_taken, value_pieces_taken, and list_pieces_taken

for (i in c(1:length(script1_white_moves))) {
  white_move = script1_white_moves[i]
  #Step 1: Find the moves where a piece was taken (all the moves that have an x in the term)
  if(grepl("x", white_move, fixed=TRUE)) {
    
    
    #Step 2: Extract the move number of the take move and the piece that took \
    ###Example: axb5 leads to the piece_capturer = a & board_loc = b5
    move_num <<- i
    piece_capturer <<- strsplit(white_move, "[x]")[[1]][1]
    board_loc <<- strsplit(white_move, "[x]")[[1]][2]
    
    
    #Step 3: Identify which piece it took by iterating backwards through black pieces, 
    ##if piece_taken is "", its a pawn
    
    #Intialize, used for later in case taken piece hasn't moved
    piece_taken <<- "RESET"

    for (j in c((move_num-1):1)) {
      black_move <- script1_black_moves[j]
      piece_select = strsplit(black_move, board_loc)[[1]][1]
      
      
      if (grepl(board_loc, black_move, fixed = TRUE)) {
        #take out excess x (which indicated a previous take)
        piece_taken <<- str_replace(piece_select, 'x', '')
        #if successful piece found, break loop
        break
      }
    }
    
    
    ###Edge case: piece that was taken has not moved yet
    if (piece_taken == "RESET") {
      piece_taken <<- original_piece_locations("black", board_loc)
    }
  
  #step 4: Add values to dataframe
  if(i == move_num) {
    piece_capturer_name = scriptname2fullname_func(piece_capturer)
    piece_taken_name = scriptname2fullname_func(piece_taken)
    piece_taken_value = name2value_func(piece_taken)
    
    game_takes[piece_capturer_name, 'num_pieces_taken'] = 
      game_takes[piece_capturer_name, 'num_pieces_taken'] + 1
    
    game_takes[piece_capturer_name, 'value_pieces_taken'] = 
      game_takes[piece_capturer_name, 'value_pieces_taken'] + piece_taken_value
    
    string = game_takes[piece_capturer_name, 'list_pieces_taken']
    new_string = paste(string, piece_taken_name)
    game_takes[piece_capturer_name, 'list_pieces_taken'] = new_string
    
    }
  }
}

game_takes
```


