---
title: "ChessPieceValuation"
output: html_document
---

```{r}
chess_summ = read.csv('../Data/chess_summ.csv')
chess_summ
```

```{r}
chess_summ_valpiecestaken = chess_summ[,c(1,26:31, 50:55)]


chess_summ_valpiecestaken = chess_summ_valpiecestaken %>%
  mutate(pawn_value_pieces_taken = (white_pawn_value_pieces_taken +
           black_pawn_value_pieces_taken) / 2) %>%
  mutate(knight_value_pieces_taken = (white_knight_value_pieces_taken +
           black_knight_value_pieces_taken) / 2) %>%
  mutate(bishop_value_pieces_taken = (white_bishop_value_pieces_taken +
           black_bishop_value_pieces_taken) / 2) %>%
  mutate(rook_value_pieces_taken = (white_rook_value_pieces_taken +
           black_rook_value_pieces_taken) / 2) %>%
  mutate(queen_value_pieces_taken = (white_queen_value_pieces_taken +
           black_queen_value_pieces_taken) / 2)


chess_sum_checks = chess_summ[,c(1,14:18, 38:42)] 

chess_sum_checks = chess_sum_checks %>%
  mutate(pawn_num_checks = (white_pawn_num_checks +
           black_pawn_num_checks) / 2) %>%
  mutate(knight_num_checks = (white_knight_num_checks +
           black_knight_num_checks) / 2) %>%
  mutate(bishop_num_checks = (white_bishop_num_checks +
           black_bishop_num_checks) / 2) %>%
  mutate(rook_num_checks = (white_rook_num_checks +
           black_rook_num_checks) / 2) %>%
  mutate(queen_num_checks = (white_queen_num_checks +
           black_queen_num_checks) / 2)
```

```{r}
chess_fullsumm = chess_summ_valpiecestaken[,c(1, 14:18)]
chess_fullsumm[,7:11] = chess_sum_checks[, c(12:16)]

chess_fullsumm = chess_fullsumm[, c(1,2,7,3,8,4,9,5,10,6,11)]
chess_fullsumm
```

```{r}
newdf = data.frame(matrix(nrow=30,ncol=1))
newdf$rating_category = rep(chess_fullsumm$rating_category, 5)
newdf$piece = c(rep('Pawn', 6), rep('Knight', 6), rep('Bishop', 6), rep('Rook', 6), rep('Queen', 6))

newdf$value_pieces_taken = c(chess_fullsumm$pawn_value_pieces_taken,
                             chess_fullsumm$knight_value_pieces_taken,
                             chess_fullsumm$bishop_value_pieces_taken,
                             chess_fullsumm$rook_value_pieces_taken,
                             chess_fullsumm$queen_value_pieces_taken)

newdf$num_checks = c(chess_fullsumm$pawn_num_checks,
                             chess_fullsumm$knight_num_checks,
                             chess_fullsumm$bishop_num_checks,
                             chess_fullsumm$rook_num_checks,
                             chess_fullsumm$queen_num_checks)

newdf = newdf[,2:5]
newdf
```

```{r}
ggplot(newdf, aes(value_pieces_taken, num_checks, color = piece, size = rating_category)) + 
  geom_point() + 
  labs(
    title = 'Value of Pieces Taken vs Number of Checks',
    x = 'Value of Pieces Taken',
    y = 'Number of Checks'
  )
```

Assuming there was a finite sum of pieces - how would it be split for different levels?
Let's take 9+(5*2)+(3*4)+(8*1) = 39

```{r}
chess_fullsumm$all_value = chess_fullsumm$pawn_value_pieces_taken +
  chess_fullsumm$knight_value_pieces_taken +
  chess_fullsumm$bishop_value_pieces_taken + 
  chess_fullsumm$rook_value_pieces_taken + 
  chess_fullsumm$queen_value_pieces_taken

chess_fullsumm$all_checks = chess_fullsumm$pawn_num_checks +
  chess_fullsumm$knight_num_checks +
  chess_fullsumm$bishop_num_checks + 
  chess_fullsumm$rook_num_checks + 
  chess_fullsumm$queen_num_checks


chess_prop = data.frame(chess_fullsumm)

chess_prop[, c(2,4,6,8,10)] = chess_prop[, c(2,4,6,8,10)] / chess_prop$all_value
chess_prop[, c(3,5,7,9,11)] = chess_prop[, c(3,5,7,9,11)] / chess_prop$all_checks

chess_prop$pawn_prop_val = (chess_prop$pawn_num_checks + chess_prop$pawn_value_pieces_taken)
chess_prop$knight_prop_val = chess_prop$knight_num_checks + chess_prop$knight_value_pieces_taken
chess_prop$bishop_prop_val = chess_prop$bishop_num_checks + chess_prop$bishop_value_pieces_taken
chess_prop$rook_prop_val = chess_prop$rook_num_checks + chess_prop$rook_value_pieces_taken
chess_prop$queen_prop_val = chess_prop$queen_num_checks + chess_prop$queen_value_pieces_taken

chess_prop[1,14:18] = (chess_prop[1,14:18] / sum(chess_prop[1,14:18])) * 39
chess_prop[2,14:18] = (chess_prop[2,14:18] / sum(chess_prop[2,14:18])) * 39
chess_prop[3,14:18] = (chess_prop[3,14:18] / sum(chess_prop[3,14:18])) * 39
chess_prop[4,14:18] = (chess_prop[4,14:18] / sum(chess_prop[4,14:18])) * 39
chess_prop[5,14:18] = (chess_prop[5,14:18] / sum(chess_prop[5,14:18])) * 39
chess_prop[6,14:18] = (chess_prop[6,14:18] / sum(chess_prop[6,14:18])) * 39

chess_prop$pawn_prop_val = chess_prop$pawn_prop_val / 8
chess_prop$knight_prop_val = chess_prop$knight_prop_val / 2
chess_prop$bishop_prop_val = chess_prop$bishop_prop_val / 2
chess_prop$rook_prop_val = chess_prop$rook_prop_val / 2


#chess_prop[7,] = c('Standard', 1,3,3,5,9)
```

```{r}
first_values = chess_prop[,c(1,14:18)]
first_values[7,] = c('Standard',1,3,3,5,9)
first_values[,2:6] = sapply(first_values[,2:6], as.numeric)


dfm <- melt(first_values[,colnames(first_values)],
            id.vars = 1)

ggplot(dfm, aes(fill = rating_category, y = value, x = variable)) + 
  geom_bar(position="dodge", stat="identity") + 
  labs(
    title = 'First Valuations of Pieces for Every Level',
    subtitle = 'Just using Value of Pieces Taken and Number of Checks, both proportional',
    x = 'Pieces',
    y = 'Value - Proposed or Real'
  )

```

```{r}
output = first_values[c(1,6,7), ]
library(gridExtra)
pdf("../Images/first_valuation.pdf", height=11, width=8.5)
grid.table(output)
dev.off()
```

